name: documentation

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build documentation from modules
        run: |
          echo "MongoDB Ansible Modules Documentation" > index.html
          find plugins/modules -type f -name 'mongodb_*.py' -exec bash -c 'echo "<a href=$(basename {} .py).rst>$(basename "{}" ".py")</a>"' \; >> index.html
          find plugins/modules -type f -name 'mongodb_*.py' -exec bash -c 'ansible-doc -M $(dirname "{}") $(basename "{}" ".py") > "$(basename "{}" ".py").rst"' \;

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
