name: documentation

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Checkout
        uses: actions/checkout@v1

      #- name: Install ansible-base (devel) - Docker image now has ansible pre-installed?
      #  run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Build collection
        run: ansible-galaxy collection build .

      - name: Install collection
        run: ansible-galaxy collection install community-mongodb-*.tar.gz

      - name: Install ansible-doc-extractor
        run: pip install wheel setuptools ansible-doc-extractor --upgrade

      - name: Install rstdoc
        run: pip install -v rstdoc

      - name: Create docs dir
        run: mkdir docs

      - name: Create rst files from modules
        run: ansible-doc-extractor ./docs plugins/modules/mongodb_*.py

      - name: Create module index document
        run: |
          echo "# MongoDB Ansible Collection Documentation" > docs/index.md
          echo "## Modules" >> docs/index.md
          find plugins/modules -type f -name 'mongodb_*.py' -exec bash -c 'echo "- [$(basename "{}" ".py")]($(basename {} .py).html)"' \; >> docs/index.md
          echo "## Lookup" >> docs/index.md
          echo "TODO" >> docs/index.md
          echo "## Cache" >> docs/index.md
          echo "TODO" >> docs/index.md          

      - name: Create module html documents from rst files
        run: |
          find ./docs -type f -name 'mongodb_*.rst' -exec bash -c 'rstdoc {} "docs/$(basename "{}" ".rst").html" rst_html' \;

      - name: Remove intermediary rst docs
        run: rm docs/*.rst

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
